### ISSUE TITLE
設定ファイルの形式を変える

### ISSUE THREAD

**Issue by ara-ta3** [ara-ta3/WebMetricsTracker#37]
ga4だけではなく他のも取得したい場合に備える

**Comment by ara-ta3** [comment]
@claude yamlだとどうですか

**Comment by ara-ta3** [comment]
@claude ではeemeli/yamlを利用して設定ファイルをEnvからyamlファイルへと移行してください
yamlは以下の形式で、SearchConsoleは一旦なしの状態でリファクタリングする形で進めてください

```yaml
# config/websites.yaml
websites:
  - name: "メインサイト"
    # GA4とSearchConsole両方設定
    metrics:
      ga4:
        propertyId: "123456789"
      searchConsole:
        siteUrl: "https://example.com"
  
  - name: "ブログサイト" 
    # GA4のみ設定（SearchConsoleなし）
    metrics:
      ga4:
        propertyId: "987654321"
```

また、コメントにてCI用の設定ファイルはどうすると良いかアドバイスをください
今のところyamlファイルをBase64エンコードして、GitHubActionsのSecretsの入れるのが無難かなと思っています
